### ISSUE TITLE
Hi, I have a question about your work!

### ISSUE THREAD

**Issue by bigbigpark** [Subh85330/Online-Trajectory-Generation-With-MPC-for-Non-Holonomic-Robots#1]
Thanks for showing your challenging work! <br/>

Is there any publications or code materials of [Modelling-And-Control-Of-Multi-Mobile-Robots-Using-MPC](https://github.com/Subh85330/Modelling-And-Control-Of-Multi-Mobile-Robots-Using-MPC) ? <br/>
I'm very interested in MPC-based control of mobile robots! <br/>

**Comment by Subh85330** [comment]
Yes, What is your question?

**Comment by Subh85330** [comment]
Thanks, 
I have publish the code in the repository
